export type UrgencyLevel = 'Very High' | 'High' | 'Medium' | 'Low';
export type DifficultyLevel = 'BASİT' | 'BASİT ÜSTÜ' | 'ORTA' | 'ZOR' | 'ÇOK ZOR';
export type ReportStatus = 'pending' | 'done' | 'cancelled';

export interface User {
  id: string;
  name: string;
  email: string;
  phone?: string;      // Phone number for Jabber click-to-call
  emoji?: string;     // New property for selected emoji
  role?: string;      // Optional role for reporting
}

export interface Department {
  id: string;
  name: string;
}

export type CampaignStatus = 'Planlandı' | 'Tamamlandı' | 'İptal Edildi';

export interface EventHistoryItem {
  date: Date;
  action: string;
  oldStatus?: CampaignStatus;
  newStatus?: CampaignStatus;
  changedBy?: string;
}

export interface CalendarEvent {
  id: string;
  date: Date;
  originalDate?: Date; // First assigned date (for duration calculation, doesn't change on reschedule)
  title: string;
  description?: string;
  urgency: UrgencyLevel; // Changed from platform
  difficulty?: DifficultyLevel; // New property for campaign difficulty
  assigneeId?: string; // ID of the assigned User
  departmentId?: string; // ID of the requesting Department
  status?: CampaignStatus;
  createdAt?: Date;
  updatedAt?: Date;
  history?: EventHistoryItem[];
  note?: string; // Campaign delay note or sticky note
  requiresReport?: boolean; // Whether this campaign needs a report when completed

  // Report Tracking Fields
  reportStatus?: 'pending' | 'done';      // Report status
  reportDueDate?: Date;                   // Campaign completion + 30 days
  reportCompletedAt?: Date;               // When the report was completed
  reportCompletedBy?: string;             // ID of the person who completed the report
}

export interface UrgencyConfig {
  label: string;
  colorBg: string;
  colorBorder: string;
  colorText: string;
}

export interface DifficultyConfig {
  label: string;
  color: string;
  textColor: string;
}

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  date: Date;
  isRead: boolean;
  type: 'email' | 'system';
}

export interface ActivityLog {
  id: string;
  message: string;
  timestamp: Date;
}

export interface ToastMessage {
  id: string;
  message: string;
  type: 'success' | 'info';
}

export interface DepartmentUser {
  id: string;
  username: string;
  // password: string; // DEPRECATED: Moved to Firebase Auth
  uid?: string; // Firebase Auth UID
  departmentId: string;
  isDesigner?: boolean;
  isKampanyaYapan?: boolean;
  isBusinessUnit?: boolean; // New role for requesting work
  isAnalitik?: boolean; // Analytics role - can manage analytics tasks
  email?: string; // Contact email for notifications
  hasDefaultPassword?: boolean; // True if user hasn't changed from default password
  createdAt: Date;
  lastSeen?: Date; // For tracking online status
}

export interface WorkRequest {
  id: string;
  title: string;
  description?: string;
  urgency: UrgencyLevel;
  targetDate: Date;
  departmentId: string; // The department making the request
  requesterEmail?: string; // Email of the requester for notifications
  status: 'pending' | 'approved' | 'rejected';
  createdAt: Date;
  rejectedReason?: string;
}

export interface Announcement {
  id: string;
  title: string;
  content: string;
  createdAt: Date;
  createdBy: string;
  visibleTo: 'admin' | 'kampanya' | 'all';
  readBy: string[];
}

export interface MonthlyChampion {
  userId: string; // Deprecated, kept for backwards compatibility
  userIds: string[]; // Array of winner IDs (supports ties)
  month: string; // Format: YYYY-MM
  campaignCount: number;
  calculatedAt: Date;
}

// Report entity - stored in separate 'reports' collection
export interface Report {
  id: string;
  title: string;                    // Report name
  campaignId?: string;              // Related campaign ID (for auto-generated reports)
  campaignTitle?: string;           // Campaign title (reference)
  assigneeId?: string;              // Assigned person
  dueDate: Date;                    // Report due date
  status: ReportStatus;             // Report status
  completedAt?: Date;               // Completion date
  completedBy?: string;             // Completer person ID
  createdAt: Date;
  updatedAt?: Date;
  isAutoGenerated?: boolean;        // Was auto-generated from campaign completion
}

// Analytics User - separate from campaign personnel
export interface AnalyticsUser {
  id: string;
  name: string;
  email: string;
  emoji?: string;
  phone?: string;  // Phone number for contact
}

// Analytics Task - for analytics calendar
export interface AnalyticsTask {
  id: string;
  title: string;           // İşin Adı
  date: Date;
  urgency: UrgencyLevel;   // Aciliyet
  difficulty?: 'Kolay' | 'Orta' | 'Zor';  // Zorluk Seviyesi (only visible to admins)
  notes?: string;          // Notlar
  assigneeId?: string;     // Assigned AnalyticsUser.id
  status?: CampaignStatus; // Planlandı, Tamamlandı, İptal Edildi
  createdAt?: Date;
  updatedAt?: Date;
  history?: EventHistoryItem[];
}